version: "3"
services:
  server:
    build: server
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/e_commerce"
      PORT: "5000"
    ports:
      - 5000:5000
  client:
    build: client
    environment:
      VUE_APP_API_URL: "http://localhost:5000"
      PORT: "8080"
    ports:
      - 8080:8080
  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017
